---
exclude_paths: [
    '*',
    'doc/*',
    'Web/*',
    'Security/*',
    'DevelopmentWebServer/*',
    'Assets.xcassets/*',
    'Base.lproj/*',
    'Preview Content/*',
    'basicmobileapp.xcodeproj/*'
]
