---
exclude_paths: [
    '*',
    'Assets.xcassets/*',
    'Base.lproj/*',
    'DevelopmentWebServer/*',
    'doc/*',
    'finalmobileapp.xcodeproj/**',
    'Preview Content/*',
    'Security/*',
    'Web/*'
]
